spring:
  config:
    activate:
      on-profile: lightsail

server:
  forward-headers-strategy: framework

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000,https://melissa-playground.nararia03.dev,https://dev.melissa7.shop,https://lightsail.melissahttps.cloud}
