server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${AWS_DB_URL}:3306/melissa_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=true&requireSSL=true #jdbc:mysql://127.0.0.1:3306/melissa_db  #
    username: ${AWS_DB_USERNAME} #root #
    password: ${AWS_DB_PASSWORD} #12341234 #
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

cloud:
  aws:
    s3:
      bucket: melissa-s3
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}

security:
  jwt:
    secret-key: ${MELISSA_JWT_SECRET_KEY}